# Generated by Django 3.1.2 on 2020-10-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.CharField(max_length=30)),
            ],
        ),
    ]
